[project]
name = "gen-data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.4"
dependencies = [
    "aiomysql>=0.2.0",
    "dotenv>=0.9.9",
    "mcp>=1.4.1",
]
